language: go

go:
  - tip

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci -package=github.com/knq/ini,github.com/knq/ini/parser ./...
#  - go test -v ./...
